attributes = {
    'workbooks'    : [
        'id',
        'content_url',
        'created_at',
        'description',
        'name',
        'owner_id',
        'project_id',
        'project_name',
        'show_tabs',
        'size',
        'tags',
        'updated_at',
        'webpage_url',
        # 'connections',
        # 'data_acceleration_config',
        # 'from_response',
        # 'pdf',
        # 'permissions',
        # 'preview_image',
        # 'views',
    ],
    'connections'  : [
        'id',
        'connection_type',
        'datasource_id',
        'datasource_name',
        'embed_password',
        'password',
        'server_address',
        'server_port',
        'username',
    ],
    'views'        : [
        'id',
        'content_url',
        'created_at',
        'name',
        'owner_id',
        'project_id',
        'sheet_type',
        'tags',
        'updated_at',
        'workbook_id',
        # 'csv',
        # 'from_response',
        # 'from_xml_element',
        # 'image',
        # 'pdf',
        # 'permissions',
        # 'preview_image',
        # 'total_views',
    ],
    'datasources'  : [
        'ask_data_enablement',
        'certification_note',
        'certified',
        'content_url',
        'created_at',
        'datasource_type',
        'description',
        'encrypt_extracts',
        'has_extracts',
        'id',
        'name',
        'owner_id',
        'project_id',
        'project_name',
        'tags',
        'updated_at',
        'use_remote_query_agent',
        'webpage_url',
        # 'AskDataEnablement',
        # 'connections',
        # 'from_response',
        # 'permissions',
    ],
    'projects'     : [
        'id',
        'content_permissions',
        'description',
        'name',
        'parent_id',
        # 'default_datasource_permissions',
        # 'default_flow_permissions',
        # 'default_workbook_permissions',
        # 'from_response',
        # 'is_default',
        # 'permissions'
    ],
    'users'        : [
        'id',
        'auth_setting',
        'domain_name',
        'email',
        'external_auth_user_id',
        'fullname',
        'last_login',
        'name',
        'site_role',
        'tag_name',
        # 'as_reference',
        # 'Auth',
        # 'favorites',
        # 'from_response',
        # 'Roles',
        # 'to_reference',
        # 'workbooks'
    ],
    'groups'       : [
        'id',
        'domain_name',
        'license_mode',
        'minimum_site_role',
        'name',
        'tag_name',
        # 'as_reference',
        # 'from_response',
        # 'to_reference',
        # 'users'
    ],
    'subscriptions': ['id', 'schedule_id', 'subject', 'target', 'user_id'],
    'schedules'    : ['id', 'execution_order', 'interval_item', 'name', 'priority', 'schedule_type'],
    'revisions'    : [
        'revision_number',
        'published_at',
        'deleted',
        'current',
        'size_in_bytes',
        'publisher_id',
        'publisher_name',
    ]
}
